export const emptyResumeData = {
    personal: {
        fullName: '',
        title: '',
        email: '',
        phone: '',
        location: '',
        linkedin: '',
        github: '',
        portfolio: '',
        photo: '',
    },
    summary: '',
    education: [],
    experience: [],
    projects: [],
    skills: {
        programming: [],
        frontend: [],
        backend: [],
        databases: [],
        frameworks: [],
        tools: [],
        other: [],
    },
    certifications: [],
    achievements: [],
    languages: [],
    customSections: [],
    sectionOrder: [
        'personal',
        'summary',
        'education',
        'experience',
        'projects',
        'skills',
        'certifications',
        'achievements',
        'languages',
        'custom',
    ],
};
